### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by byelik** [adamgit/Unity-delaunay#4]
Hi. I have a question. How can I build a mesh? How to get triangles?
Thanks in advance

**Comment by cjburkey01** [comment]
Wondering the same thing, I can't see any reasonable way to do it without having to gather all the vertices in the regions generated and triangulate them using another method

**Comment by adamgit** [comment]
Everything you need to know is in the readme.

When I get back to desktop, I'll delete this repository : everyone who was using it has had plenty of time to migrate away by now.
